{% set name = "pep621" %}
{% set version = "0.4.0.post2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pep621-{{ version }}.tar.gz
  sha256: 24119f0f41faace77e36daae01ec70ab90596d78b6f2bc465ef8739dc63439f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - packaging >=19.0
    - python >=3.7

test:
  imports:
    - pep621
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pep621/
  summary: PEP 621 metadata parsing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
